version: '3.5'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --cert-file cert.crt
    ports:
      - 8000:8000
    environment:
      'DB_NAME': 'postgres'
      'DB_USER': 'postgres'
      'DB_HOST': db
      'DB_PORT': 5432
      'DB_PASSWORD': 'postgres'
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    environment:
      'POSTGRES_PASSWORD': 'postgres'
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080