name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Build the docker-compose stack
      run: docker-compose up -d

    - name: List containers
      run: docker ps

    - name: Run Tests
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker exec $(docker ps | grep web | awk '{print $1}') python ./manage.py test
